#!/bin/bash

readonly QCONFIG_HOME="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd
)"
readonly QCONFIG_BASH_CONF="${QCONFIG_HOME}"/bash
readonly QCONFIG_BASH_ALIASES="${QCONFIG_BASH_CONF}"/bashrc/10aliases.sh
readonly QCONFIG_VIM_CONF="${QCONFIG_HOME}"/vim
readonly QCONFIG_VIMRC="${HOME}"/.vim/vimrc
readonly QCONFIG_TMP_BASHRC=/tmp/bashrc
readonly QCONFIG_TMP_ALIASES=/tmp/aliases.sh


qconfig_bash() {
  qconfig_make_aliases

  cat "${QCONFIG_BASH_CONF}"/bashrc/*.sh >> "${QCONFIG_TMP_BASHRC}"
}


qconfig_vim() {
  local vim_plugin_dir="${HOME}"/.vim/pack/dist/start

  mkdir -p "${vim_plugin_dir}"
  cp -R "${QCONFIG_VIM_CONF}"/* "${HOME}"/.vim/

  for p in "${QCONFIG_VIM_PLUGINS[@]}"; do
    local reponame="${p##*/}"
    local install_dir="${reponame%.*}"
    git clone "${p}" "${vim_plugin_dir}"/"${install_dir}"
  done
}


qconfig_dep_reminder() {
  yellow_echo "Remember, check if the following executables are present"
  yellow_echo "If they are not, be sure to install them so everything works"

  echo -n "Bash: "
  red_echo "${QCONFIG_BASH_DEPS[@]}"
  echo -n "Vim: "
  red_echo "${QCONFIG_VIM_DEPS[@]}"
}


main() {
  source "${QCONFIG_HOME}"/lib/utils.sh

  case "${OSTYPE}" in
    "darwin"*)
      source "${QCONFIG_BASH_CONF}"/platform/darwin.sh
      ;;
    "linux-gnu")
      source "${QCONFIG_BASH_CONF}"/platform/linux.sh
      qconfig_check_linux
      ;;
    *)
      die "Unsupported platform"
  esac

  source "${QCONFIG_BASH_CONF}"/mkalias.sh
  source "${QCONFIG_BASH_CONF}"/deps.sh
  source "${QCONFIG_VIM_CONF}"/vim-plugins.sh
  source "${QCONFIG_VIM_CONF}"/deps.sh

  qconfig_bash
  qconfig_vim
  qconfig_dep_reminder

  cp -f "${QCONFIG_TMP_BASHRC}" "${QCONFIG_BASHRC}"

  echo "Run the following when ready:"
  echo "source ${QCONFIG_BASHRC}"
}

main

trap finish EXIT
